// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9VGScNGdf_md34NW2ZadWd1XXhR53Nuo',
    appId: '1:948964175027:web:166b063b49c03259c8d4c6',
    messagingSenderId: '948964175027',
    projectId: 'magic-recipe-1bbfe',
    authDomain: 'magic-recipe-1bbfe.firebaseapp.com',
    storageBucket: 'magic-recipe-1bbfe.appspot.com',
    measurementId: 'G-CG1EPTJWD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFiMnl2pCu6-bOs8Dl4BFN7rXFcQKk-L0',
    appId: '1:948964175027:android:3109b74fdaa3f5e5c8d4c6',
    messagingSenderId: '948964175027',
    projectId: 'magic-recipe-1bbfe',
    storageBucket: 'magic-recipe-1bbfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKlx07FjcIO1iKYugwIny7kngigYxqgU0',
    appId: '1:948964175027:ios:9cad0ad5cbb0eea3c8d4c6',
    messagingSenderId: '948964175027',
    projectId: 'magic-recipe-1bbfe',
    storageBucket: 'magic-recipe-1bbfe.appspot.com',
    iosClientId: '948964175027-k5pl5qo8tkc0ujucdtsmerspfcrffhv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKlx07FjcIO1iKYugwIny7kngigYxqgU0',
    appId: '1:948964175027:ios:9cad0ad5cbb0eea3c8d4c6',
    messagingSenderId: '948964175027',
    projectId: 'magic-recipe-1bbfe',
    storageBucket: 'magic-recipe-1bbfe.appspot.com',
    iosClientId: '948964175027-k5pl5qo8tkc0ujucdtsmerspfcrffhv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );
}
